FROM gradle:8.7.0-jdk21-alpine AS build
WORKDIR /home/app
COPY ../. /home/app
RUN gradle clean build

FROM eclipse-temurin:21-jdk-alpine

LABEL authors="vrudas"

WORKDIR /home/app
COPY --from=build /home/app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
