spring.application.name: docker-playground-application

server.shutdown: graceful

management.server.port: 8090
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

spring.datasource.url: jdbc:postgresql://localhost:5432/dvdrental
spring.datasource.username: postgres
spring.datasource.password: postgres

spring.docker.compose.enabled: true
spring.main.lazy-initialization: true
